export const data =[
    {
    "country": "China",
    "cases": 81285,
    "todayCases": 67,
    "deaths": 3287,
    "todayDeaths": 6,
    "recovered": 74051,
    "active": 3947,
    "critical": 1235,
    "casesPerOneMillion": 56,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Italy",
    "cases": 74386,
    "todayCases": 5210,
    "deaths": 7503,
    "todayDeaths": 683,
    "recovered": 9362,
    "active": 57521,
    "critical": 3489,
    "casesPerOneMillion": 1230,
    "deathsPerOneMillion": 124
    },
    {
    "country": "USA",
    "cases": 66048,
    "todayCases": 11192,
    "deaths": 944,
    "todayDeaths": 164,
    "recovered": 394,
    "active": 64710,
    "critical": 1452,
    "casesPerOneMillion": 200,
    "deathsPerOneMillion": 3
    },
    {
    "country": "Spain",
    "cases": 49515,
    "todayCases": 7457,
    "deaths": 3647,
    "todayDeaths": 656,
    "recovered": 5367,
    "active": 40501,
    "critical": 3166,
    "casesPerOneMillion": 1059,
    "deathsPerOneMillion": 78
    },
    {
    "country": "Germany",
    "cases": 37323,
    "todayCases": 4332,
    "deaths": 206,
    "todayDeaths": 47,
    "recovered": 3547,
    "active": 33570,
    "critical": 23,
    "casesPerOneMillion": 445,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Iran",
    "cases": 27017,
    "todayCases": 2206,
    "deaths": 2077,
    "todayDeaths": 143,
    "recovered": 9625,
    "active": 15315,
    "critical": 0,
    "casesPerOneMillion": 322,
    "deathsPerOneMillion": 25
    },
    {
    "country": "France",
    "cases": 25233,
    "todayCases": 2929,
    "deaths": 1331,
    "todayDeaths": 231,
    "recovered": 3900,
    "active": 20002,
    "critical": 2827,
    "casesPerOneMillion": 387,
    "deathsPerOneMillion": 20
    },
    {
    "country": "Switzerland",
    "cases": 10897,
    "todayCases": 1020,
    "deaths": 153,
    "todayDeaths": 31,
    "recovered": 131,
    "active": 10613,
    "critical": 141,
    "casesPerOneMillion": 1259,
    "deathsPerOneMillion": 18
    },
    {
    "country": "UK",
    "cases": 9529,
    "todayCases": 1452,
    "deaths": 465,
    "todayDeaths": 43,
    "recovered": 135,
    "active": 8929,
    "critical": 163,
    "casesPerOneMillion": 140,
    "deathsPerOneMillion": 7
    },
    {
    "country": "S. Korea",
    "cases": 9137,
    "todayCases": 100,
    "deaths": 126,
    "todayDeaths": 6,
    "recovered": 3730,
    "active": 5281,
    "critical": 59,
    "casesPerOneMillion": 178,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Netherlands",
    "cases": 6412,
    "todayCases": 852,
    "deaths": 356,
    "todayDeaths": 80,
    "recovered": 3,
    "active": 6053,
    "critical": 582,
    "casesPerOneMillion": 374,
    "deathsPerOneMillion": 21
    },
    {
    "country": "Austria",
    "cases": 5588,
    "todayCases": 305,
    "deaths": 30,
    "todayDeaths": 2,
    "recovered": 9,
    "active": 5549,
    "critical": 28,
    "casesPerOneMillion": 620,
    "deathsPerOneMillion": 3
    },
    {
    "country": "Belgium",
    "cases": 4937,
    "todayCases": 668,
    "deaths": 178,
    "todayDeaths": 56,
    "recovered": 547,
    "active": 4212,
    "critical": 474,
    "casesPerOneMillion": 426,
    "deathsPerOneMillion": 15
    },
    {
    "country": "Canada",
    "cases": 3409,
    "todayCases": 617,
    "deaths": 36,
    "todayDeaths": 10,
    "recovered": 185,
    "active": 3188,
    "critical": 1,
    "casesPerOneMillion": 90,
    "deathsPerOneMillion": 1
    },
    {
    "country": "Norway",
    "cases": 3084,
    "todayCases": 218,
    "deaths": 14,
    "todayDeaths": 2,
    "recovered": 6,
    "active": 3064,
    "critical": 57,
    "casesPerOneMillion": 569,
    "deathsPerOneMillion": 3
    },
    {
    "country": "Portugal",
    "cases": 2995,
    "todayCases": 633,
    "deaths": 43,
    "todayDeaths": 10,
    "recovered": 22,
    "active": 2930,
    "critical": 61,
    "casesPerOneMillion": 294,
    "deathsPerOneMillion": 4
    },
    {
    "country": "Australia",
    "cases": 2676,
    "todayCases": 359,
    "deaths": 11,
    "todayDeaths": 3,
    "recovered": 118,
    "active": 2547,
    "critical": 11,
    "casesPerOneMillion": 105,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Brazil",
    "cases": 2554,
    "todayCases": 307,
    "deaths": 59,
    "todayDeaths": 13,
    "recovered": 2,
    "active": 2493,
    "critical": 18,
    "casesPerOneMillion": 12,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Sweden",
    "cases": 2526,
    "todayCases": 227,
    "deaths": 62,
    "todayDeaths": 22,
    "recovered": 16,
    "active": 2448,
    "critical": 158,
    "casesPerOneMillion": 250,
    "deathsPerOneMillion": 6
    },
    {
    "country": "Turkey",
    "cases": 2433,
    "todayCases": 561,
    "deaths": 59,
    "todayDeaths": 15,
    "recovered": 26,
    "active": 2348,
    "critical": 136,
    "casesPerOneMillion": 29,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Israel",
    "cases": 2369,
    "todayCases": 439,
    "deaths": 5,
    "todayDeaths": 2,
    "recovered": 58,
    "active": 2306,
    "critical": 37,
    "casesPerOneMillion": 274,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Malaysia",
    "cases": 1796,
    "todayCases": 172,
    "deaths": 20,
    "todayDeaths": 4,
    "recovered": 199,
    "active": 1577,
    "critical": 64,
    "casesPerOneMillion": 55,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Denmark",
    "cases": 1724,
    "todayCases": 133,
    "deaths": 34,
    "todayDeaths": 2,
    "recovered": 1,
    "active": 1689,
    "critical": 87,
    "casesPerOneMillion": 298,
    "deathsPerOneMillion": 6
    },
    {
    "country": "Czechia",
    "cases": 1654,
    "todayCases": 260,
    "deaths": 6,
    "todayDeaths": 3,
    "recovered": 10,
    "active": 1638,
    "critical": 19,
    "casesPerOneMillion": 154,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Ireland",
    "cases": 1564,
    "todayCases": 235,
    "deaths": 9,
    "todayDeaths": 2,
    "recovered": 5,
    "active": 1550,
    "critical": 39,
    "casesPerOneMillion": 317,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Luxembourg",
    "cases": 1333,
    "todayCases": 234,
    "deaths": 8,
    "todayDeaths": 0,
    "recovered": 6,
    "active": 1319,
    "critical": 3,
    "casesPerOneMillion": 2129,
    "deathsPerOneMillion": 13
    },
    {
    "country": "Japan",
    "cases": 1307,
    "todayCases": 114,
    "deaths": 45,
    "todayDeaths": 2,
    "recovered": 310,
    "active": 952,
    "critical": 57,
    "casesPerOneMillion": 10,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Ecuador",
    "cases": 1211,
    "todayCases": 129,
    "deaths": 29,
    "todayDeaths": 2,
    "recovered": 3,
    "active": 1179,
    "critical": 2,
    "casesPerOneMillion": 69,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Chile",
    "cases": 1142,
    "todayCases": 220,
    "deaths": 3,
    "todayDeaths": 1,
    "recovered": 22,
    "active": 1117,
    "critical": 7,
    "casesPerOneMillion": 60,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Pakistan",
    "cases": 1063,
    "todayCases": 91,
    "deaths": 8,
    "todayDeaths": 1,
    "recovered": 21,
    "active": 1034,
    "critical": 5,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Poland",
    "cases": 1051,
    "todayCases": 150,
    "deaths": 14,
    "todayDeaths": 4,
    "recovered": 7,
    "active": 1030,
    "critical": 3,
    "casesPerOneMillion": 28,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Thailand",
    "cases": 934,
    "todayCases": 107,
    "deaths": 4,
    "todayDeaths": 0,
    "recovered": 70,
    "active": 860,
    "critical": 11,
    "casesPerOneMillion": 13,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Romania",
    "cases": 906,
    "todayCases": 112,
    "deaths": 17,
    "todayDeaths": 5,
    "recovered": 86,
    "active": 803,
    "critical": 18,
    "casesPerOneMillion": 47,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Saudi Arabia",
    "cases": 900,
    "todayCases": 133,
    "deaths": 2,
    "todayDeaths": 1,
    "recovered": 29,
    "active": 869,
    "critical": 0,
    "casesPerOneMillion": 26,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Finland",
    "cases": 880,
    "todayCases": 88,
    "deaths": 3,
    "todayDeaths": 2,
    "recovered": 10,
    "active": 867,
    "critical": 22,
    "casesPerOneMillion": 159,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Greece",
    "cases": 821,
    "todayCases": 78,
    "deaths": 22,
    "todayDeaths": 2,
    "recovered": 36,
    "active": 763,
    "critical": 53,
    "casesPerOneMillion": 79,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Indonesia",
    "cases": 790,
    "todayCases": 104,
    "deaths": 58,
    "todayDeaths": 3,
    "recovered": 31,
    "active": 701,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Iceland",
    "cases": 737,
    "todayCases": 89,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 56,
    "active": 679,
    "critical": 11,
    "casesPerOneMillion": 2160,
    "deathsPerOneMillion": 6
    },
    {
    "country": "Diamond Princess",
    "cases": 712,
    "todayCases": 0,
    "deaths": 10,
    "todayDeaths": 0,
    "recovered": 587,
    "active": 115,
    "critical": 15,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "South Africa",
    "cases": 709,
    "todayCases": 155,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 12,
    "active": 697,
    "critical": 2,
    "casesPerOneMillion": 12,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Russia",
    "cases": 658,
    "todayCases": 163,
    "deaths": 3,
    "todayDeaths": 2,
    "recovered": 29,
    "active": 626,
    "critical": 8,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "India",
    "cases": 657,
    "todayCases": 121,
    "deaths": 12,
    "todayDeaths": 2,
    "recovered": 43,
    "active": 602,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Philippines",
    "cases": 636,
    "todayCases": 84,
    "deaths": 38,
    "todayDeaths": 3,
    "recovered": 26,
    "active": 572,
    "critical": 1,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Singapore",
    "cases": 631,
    "todayCases": 73,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 160,
    "active": 469,
    "critical": 17,
    "casesPerOneMillion": 108,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Panama",
    "cases": 558,
    "todayCases": 115,
    "deaths": 8,
    "todayDeaths": 2,
    "recovered": 2,
    "active": 548,
    "critical": 20,
    "casesPerOneMillion": 129,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Qatar",
    "cases": 537,
    "todayCases": 11,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 41,
    "active": 496,
    "critical": 6,
    "casesPerOneMillion": 186,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Slovenia",
    "cases": 528,
    "todayCases": 48,
    "deaths": 5,
    "todayDeaths": 1,
    "recovered": 10,
    "active": 513,
    "critical": 14,
    "casesPerOneMillion": 254,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Argentina",
    "cases": 502,
    "todayCases": 115,
    "deaths": 8,
    "todayDeaths": 2,
    "recovered": 52,
    "active": 442,
    "critical": 0,
    "casesPerOneMillion": 11,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Peru",
    "cases": 480,
    "todayCases": 64,
    "deaths": 9,
    "todayDeaths": 2,
    "recovered": 1,
    "active": 470,
    "critical": 9,
    "casesPerOneMillion": 15,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Colombia",
    "cases": 470,
    "todayCases": 92,
    "deaths": 4,
    "todayDeaths": 1,
    "recovered": 8,
    "active": 458,
    "critical": 0,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Egypt",
    "cases": 456,
    "todayCases": 54,
    "deaths": 21,
    "todayDeaths": 1,
    "recovered": 95,
    "active": 340,
    "critical": 0,
    "casesPerOneMillion": 4,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Croatia",
    "cases": 442,
    "todayCases": 60,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 22,
    "active": 419,
    "critical": 6,
    "casesPerOneMillion": 108,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Bahrain",
    "cases": 419,
    "todayCases": 27,
    "deaths": 4,
    "todayDeaths": 1,
    "recovered": 177,
    "active": 238,
    "critical": 2,
    "casesPerOneMillion": 246,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Hong Kong",
    "cases": 410,
    "todayCases": 23,
    "deaths": 4,
    "todayDeaths": 0,
    "recovered": 102,
    "active": 304,
    "critical": 4,
    "casesPerOneMillion": 55,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mexico",
    "cases": 405,
    "todayCases": 38,
    "deaths": 5,
    "todayDeaths": 1,
    "recovered": 4,
    "active": 396,
    "critical": 1,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Estonia",
    "cases": 404,
    "todayCases": 35,
    "deaths": 1,
    "todayDeaths": 1,
    "recovered": 8,
    "active": 395,
    "critical": 6,
    "casesPerOneMillion": 305,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Dominican Republic",
    "cases": 392,
    "todayCases": 80,
    "deaths": 10,
    "todayDeaths": 4,
    "recovered": 3,
    "active": 379,
    "critical": 0,
    "casesPerOneMillion": 36,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Serbia",
    "cases": 384,
    "todayCases": 81,
    "deaths": 4,
    "todayDeaths": 1,
    "recovered": 15,
    "active": 365,
    "critical": 21,
    "casesPerOneMillion": 44,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Iraq",
    "cases": 346,
    "todayCases": 30,
    "deaths": 29,
    "todayDeaths": 2,
    "recovered": 103,
    "active": 214,
    "critical": 0,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Lebanon",
    "cases": 333,
    "todayCases": 15,
    "deaths": 6,
    "todayDeaths": 2,
    "recovered": 20,
    "active": 307,
    "critical": 4,
    "casesPerOneMillion": 49,
    "deathsPerOneMillion": 0
    },
    {
    "country": "UAE",
    "cases": 333,
    "todayCases": 85,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 52,
    "active": 279,
    "critical": 2,
    "casesPerOneMillion": 34,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Algeria",
    "cases": 302,
    "todayCases": 38,
    "deaths": 21,
    "todayDeaths": 2,
    "recovered": 65,
    "active": 216,
    "critical": 0,
    "casesPerOneMillion": 7,
    "deathsPerOneMillion": 0
    },
    {
    "country": "New Zealand",
    "cases": 283,
    "todayCases": 78,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 27,
    "active": 256,
    "critical": 0,
    "casesPerOneMillion": 59,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Lithuania",
    "cases": 274,
    "todayCases": 65,
    "deaths": 4,
    "todayDeaths": 2,
    "recovered": 1,
    "active": 269,
    "critical": 1,
    "casesPerOneMillion": 101,
    "deathsPerOneMillion": 1
    },
    {
    "country": "Armenia",
    "cases": 265,
    "todayCases": 16,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 16,
    "active": 249,
    "critical": 6,
    "casesPerOneMillion": 89,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Bulgaria",
    "cases": 242,
    "todayCases": 24,
    "deaths": 3,
    "todayDeaths": 0,
    "recovered": 4,
    "active": 235,
    "critical": 8,
    "casesPerOneMillion": 35,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Taiwan",
    "cases": 235,
    "todayCases": 19,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 29,
    "active": 204,
    "critical": 0,
    "casesPerOneMillion": 10,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Hungary",
    "cases": 226,
    "todayCases": 39,
    "deaths": 10,
    "todayDeaths": 1,
    "recovered": 21,
    "active": 195,
    "critical": 6,
    "casesPerOneMillion": 23,
    "deathsPerOneMillion": 1
    },
    {
    "country": "Morocco",
    "cases": 225,
    "todayCases": 55,
    "deaths": 6,
    "todayDeaths": 1,
    "recovered": 7,
    "active": 212,
    "critical": 1,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Latvia",
    "cases": 221,
    "todayCases": 24,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 220,
    "critical": 0,
    "casesPerOneMillion": 117,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Uruguay",
    "cases": 217,
    "todayCases": 28,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 217,
    "critical": 3,
    "casesPerOneMillion": 62,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Slovakia",
    "cases": 216,
    "todayCases": 12,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 7,
    "active": 209,
    "critical": 2,
    "casesPerOneMillion": 40,
    "deathsPerOneMillion": 0
    },
    {
    "country": "San Marino",
    "cases": 208,
    "todayCases": 21,
    "deaths": 21,
    "todayDeaths": 0,
    "recovered": 4,
    "active": 183,
    "critical": 12,
    "casesPerOneMillion": 6130,
    "deathsPerOneMillion": 619
    },
    {
    "country": "Costa Rica",
    "cases": 201,
    "todayCases": 24,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 197,
    "critical": 4,
    "casesPerOneMillion": 39,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Kuwait",
    "cases": 195,
    "todayCases": 4,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 43,
    "active": 152,
    "critical": 6,
    "casesPerOneMillion": 46,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Andorra",
    "cases": 188,
    "todayCases": 24,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 186,
    "critical": 6,
    "casesPerOneMillion": 2433,
    "deathsPerOneMillion": 13
    },
    {
    "country": "North Macedonia",
    "cases": 177,
    "todayCases": 29,
    "deaths": 3,
    "todayDeaths": 1,
    "recovered": 1,
    "active": 173,
    "critical": 1,
    "casesPerOneMillion": 85,
    "deathsPerOneMillion": 1
    },
    {
    "country": "Bosnia and Herzegovina",
    "cases": 176,
    "todayCases": 8,
    "deaths": 3,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 171,
    "critical": 1,
    "casesPerOneMillion": 54,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Tunisia",
    "cases": 173,
    "todayCases": 59,
    "deaths": 5,
    "todayDeaths": 1,
    "recovered": 2,
    "active": 166,
    "critical": 11,
    "casesPerOneMillion": 15,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Jordan",
    "cases": 172,
    "todayCases": 18,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 171,
    "critical": 0,
    "casesPerOneMillion": 17,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Moldova",
    "cases": 149,
    "todayCases": 24,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 146,
    "critical": 20,
    "casesPerOneMillion": 37,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Vietnam",
    "cases": 148,
    "todayCases": 14,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 17,
    "active": 131,
    "critical": 3,
    "casesPerOneMillion": 2,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Albania",
    "cases": 146,
    "todayCases": 23,
    "deaths": 5,
    "todayDeaths": 0,
    "recovered": 17,
    "active": 124,
    "critical": 3,
    "casesPerOneMillion": 51,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Burkina Faso",
    "cases": 146,
    "todayCases": 32,
    "deaths": 4,
    "todayDeaths": 0,
    "recovered": 10,
    "active": 132,
    "critical": 0,
    "casesPerOneMillion": 7,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Ukraine",
    "cases": 145,
    "todayCases": 43,
    "deaths": 5,
    "todayDeaths": 2,
    "recovered": 1,
    "active": 139,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Cyprus",
    "cases": 132,
    "todayCases": 8,
    "deaths": 3,
    "todayDeaths": 0,
    "recovered": 3,
    "active": 126,
    "critical": 3,
    "casesPerOneMillion": 109,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Faeroe Islands",
    "cases": 132,
    "todayCases": 10,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 38,
    "active": 94,
    "critical": 2,
    "casesPerOneMillion": 2701,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Malta",
    "cases": 129,
    "todayCases": 19,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 127,
    "critical": 1,
    "casesPerOneMillion": 292,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Réunion",
    "cases": 111,
    "todayCases": 17,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 110,
    "critical": 0,
    "casesPerOneMillion": 124,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Brunei",
    "cases": 109,
    "todayCases": 5,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 107,
    "critical": 1,
    "casesPerOneMillion": 249,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Venezuela",
    "cases": 106,
    "todayCases": 22,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 15,
    "active": 91,
    "critical": 2,
    "casesPerOneMillion": 4,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Sri Lanka",
    "cases": 102,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 3,
    "active": 99,
    "critical": 2,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Oman",
    "cases": 99,
    "todayCases": 15,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 17,
    "active": 82,
    "critical": 0,
    "casesPerOneMillion": 19,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Senegal",
    "cases": 99,
    "todayCases": 13,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 9,
    "active": 90,
    "critical": 0,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Cambodia",
    "cases": 96,
    "todayCases": 5,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 10,
    "active": 86,
    "critical": 1,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Ghana",
    "cases": 93,
    "todayCases": 40,
    "deaths": 4,
    "todayDeaths": 2,
    "recovered": 0,
    "active": 89,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Azerbaijan",
    "cases": 93,
    "todayCases": 6,
    "deaths": 2,
    "todayDeaths": 1,
    "recovered": 10,
    "active": 81,
    "critical": 6,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Belarus",
    "cases": 86,
    "todayCases": 5,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 29,
    "active": 57,
    "critical": 2,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Afghanistan",
    "cases": 84,
    "todayCases": 10,
    "deaths": 2,
    "todayDeaths": 1,
    "recovered": 2,
    "active": 80,
    "critical": 0,
    "casesPerOneMillion": 2,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Kazakhstan",
    "cases": 81,
    "todayCases": 9,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 81,
    "critical": 0,
    "casesPerOneMillion": 4,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Ivory Coast",
    "cases": 80,
    "todayCases": 7,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 3,
    "active": 77,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Cameroon",
    "cases": 75,
    "todayCases": 9,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 72,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Georgia",
    "cases": 75,
    "todayCases": 5,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 10,
    "active": 65,
    "critical": 1,
    "casesPerOneMillion": 19,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Guadeloupe",
    "cases": 73,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 72,
    "critical": 4,
    "casesPerOneMillion": 182,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Palestine",
    "cases": 71,
    "todayCases": 11,
    "deaths": 1,
    "todayDeaths": 1,
    "recovered": 16,
    "active": 54,
    "critical": 0,
    "casesPerOneMillion": 14,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Martinique",
    "cases": 66,
    "todayCases": 9,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 65,
    "critical": 7,
    "casesPerOneMillion": 176,
    "deathsPerOneMillion": 3
    },
    {
    "country": "Trinidad and Tobago",
    "cases": 60,
    "todayCases": 3,
    "deaths": 1,
    "todayDeaths": 1,
    "recovered": 0,
    "active": 59,
    "critical": 0,
    "casesPerOneMillion": 43,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Uzbekistan",
    "cases": 60,
    "todayCases": 10,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 60,
    "critical": 4,
    "casesPerOneMillion": 2,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Cuba",
    "cases": 57,
    "todayCases": 9,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 55,
    "critical": 2,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Montenegro",
    "cases": 53,
    "todayCases": 6,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 52,
    "critical": 1,
    "casesPerOneMillion": 84,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Honduras",
    "cases": 52,
    "todayCases": 22,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 52,
    "critical": 0,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Nigeria",
    "cases": 51,
    "todayCases": 7,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 48,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Liechtenstein",
    "cases": 51,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 51,
    "critical": 0,
    "casesPerOneMillion": 1338,
    "deathsPerOneMillion": 0
    },
    {
    "country": "DRC",
    "cases": 48,
    "todayCases": 3,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 46,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mauritius",
    "cases": 48,
    "todayCases": 6,
    "deaths": 2,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 46,
    "critical": 1,
    "casesPerOneMillion": 38,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Channel Islands",
    "cases": 46,
    "todayCases": 10,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 46,
    "critical": 0,
    "casesPerOneMillion": 265,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Kyrgyzstan",
    "cases": 44,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 44,
    "critical": 0,
    "casesPerOneMillion": 7,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Rwanda",
    "cases": 41,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 41,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Bangladesh",
    "cases": 39,
    "todayCases": 0,
    "deaths": 5,
    "todayDeaths": 1,
    "recovered": 7,
    "active": 27,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Bolivia",
    "cases": 38,
    "todayCases": 9,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 38,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Paraguay",
    "cases": 37,
    "todayCases": 10,
    "deaths": 3,
    "todayDeaths": 1,
    "recovered": 0,
    "active": 34,
    "critical": 1,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mayotte",
    "cases": 36,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 36,
    "critical": 0,
    "casesPerOneMillion": 132,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Monaco",
    "cases": 31,
    "todayCases": 8,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 30,
    "critical": 0,
    "casesPerOneMillion": 790,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Macao",
    "cases": 30,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 10,
    "active": 20,
    "critical": 0,
    "casesPerOneMillion": 46,
    "deathsPerOneMillion": 0
    },
    {
    "country": "French Guiana",
    "cases": 28,
    "todayCases": 5,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 6,
    "active": 22,
    "critical": 0,
    "casesPerOneMillion": 94,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Kenya",
    "cases": 28,
    "todayCases": 3,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 27,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Jamaica",
    "cases": 26,
    "todayCases": 5,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 23,
    "critical": 0,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Gibraltar",
    "cases": 26,
    "todayCases": 11,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 5,
    "active": 21,
    "critical": 0,
    "casesPerOneMillion": 772,
    "deathsPerOneMillion": 0
    },
    {
    "country": "French Polynesia",
    "cases": 25,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 25,
    "critical": 0,
    "casesPerOneMillion": 89,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Guatemala",
    "cases": 24,
    "todayCases": 3,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 4,
    "active": 19,
    "critical": 0,
    "casesPerOneMillion": 1,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Isle of Man",
    "cases": 23,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 23,
    "critical": 0,
    "casesPerOneMillion": 270,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Togo",
    "cases": 23,
    "todayCases": 3,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 22,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Aruba",
    "cases": 19,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 18,
    "critical": 0,
    "casesPerOneMillion": 178,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Madagascar",
    "cases": 19,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 19,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Barbados",
    "cases": 18,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 18,
    "critical": 0,
    "casesPerOneMillion": 63,
    "deathsPerOneMillion": 0
    },
    {
    "country": "New Caledonia",
    "cases": 14,
    "todayCases": 4,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 14,
    "critical": 0,
    "casesPerOneMillion": 49,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Uganda",
    "cases": 14,
    "todayCases": 5,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 14,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "El Salvador",
    "cases": 13,
    "todayCases": 8,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 13,
    "critical": 0,
    "casesPerOneMillion": 2,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Maldives",
    "cases": 13,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 8,
    "active": 5,
    "critical": 0,
    "casesPerOneMillion": 24,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Tanzania",
    "cases": 13,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 13,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Ethiopia",
    "cases": 12,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 12,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Zambia",
    "cases": 12,
    "todayCases": 9,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 12,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Djibouti",
    "cases": 11,
    "todayCases": 8,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 11,
    "critical": 0,
    "casesPerOneMillion": 11,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Dominica",
    "cases": 11,
    "todayCases": 4,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 11,
    "critical": 0,
    "casesPerOneMillion": 153,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Saint Martin",
    "cases": 11,
    "todayCases": 3,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 11,
    "critical": 0,
    "casesPerOneMillion": 284,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mongolia",
    "cases": 10,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 10,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Equatorial Guinea",
    "cases": 9,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 9,
    "critical": 0,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Cayman Islands",
    "cases": 8,
    "todayCases": 2,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 7,
    "critical": 0,
    "casesPerOneMillion": 122,
    "deathsPerOneMillion": 15
    },
    {
    "country": "Haiti",
    "cases": 8,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 8,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Suriname",
    "cases": 8,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 8,
    "critical": 0,
    "casesPerOneMillion": 14,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Niger",
    "cases": 7,
    "todayCases": 4,
    "deaths": 1,
    "todayDeaths": 1,
    "recovered": 0,
    "active": 6,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Bermuda",
    "cases": 7,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 7,
    "critical": 0,
    "casesPerOneMillion": 112,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Namibia",
    "cases": 7,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 5,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Seychelles",
    "cases": 7,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 7,
    "critical": 0,
    "casesPerOneMillion": 71,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Curaçao",
    "cases": 6,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 37,
    "deathsPerOneMillion": 6
    },
    {
    "country": "Gabon",
    "cases": 6,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 5,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Benin",
    "cases": 6,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 6,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Greenland",
    "cases": 6,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 2,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 106,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Guyana",
    "cases": 5,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 1
    },
    {
    "country": "Bahamas",
    "cases": 5,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 13,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Fiji",
    "cases": 5,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 5,
    "critical": 0,
    "casesPerOneMillion": 6,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mozambique",
    "cases": 5,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 5,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Syria",
    "cases": 5,
    "todayCases": 4,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 5,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Cabo Verde",
    "cases": 4,
    "todayCases": 1,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 7,
    "deathsPerOneMillion": 2
    },
    {
    "country": "Congo",
    "cases": 4,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Eritrea",
    "cases": 4,
    "todayCases": 3,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 1,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Guinea",
    "cases": 4,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Vatican City",
    "cases": 4,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 4994,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Eswatini",
    "cases": 4,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 4,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Gambia",
    "cases": 3,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 1,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Sudan",
    "cases": 3,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Zimbabwe",
    "cases": 3,
    "todayCases": 0,
    "deaths": 1,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Nepal",
    "cases": 3,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 1,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Angola",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Antigua and Barbuda",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 31,
    "deathsPerOneMillion": 0
    },
    {
    "country": "CAR",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Chad",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Laos",
    "cases": 3,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Liberia",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Myanmar",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "St. Barth",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 304,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Saint Lucia",
    "cases": 3,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 16,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Sint Maarten",
    "cases": 3,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 3,
    "critical": 0,
    "casesPerOneMillion": 70,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Belize",
    "cases": 2,
    "todayCases": 1,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 5,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Bhutan",
    "cases": 2,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 3,
    "deathsPerOneMillion": 0
    },
    {
    "country": "British Virgin Islands",
    "cases": 2,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 66,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Guinea-Bissau",
    "cases": 2,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 1,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mali",
    "cases": 2,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Mauritania",
    "cases": 2,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Nicaragua",
    "cases": 2,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Saint Kitts and Nevis",
    "cases": 2,
    "todayCases": 2,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 2,
    "critical": 0,
    "casesPerOneMillion": 38,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Grenada",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Libya",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Montserrat",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 200,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Papua New Guinea",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "St. Vincent Grenadines",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 9,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Somalia",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Timor-Leste",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 0,
    "deathsPerOneMillion": 0
    },
    {
    "country": "Turks and Caicos",
    "cases": 1,
    "todayCases": 0,
    "deaths": 0,
    "todayDeaths": 0,
    "recovered": 0,
    "active": 1,
    "critical": 0,
    "casesPerOneMillion": 26,
    "deathsPerOneMillion": 0
    }
    ]

